### PR TITLE
RPM package support

### PR DESCRIPTION
**Pull request by arschedev**
Currently, the only ways we can obtain Numara on GNU/Linux are through AppImage and deb packages. 
As a Fedora user, I can't use deb packages, which forces me to use the only option left, AppImage. However, AppImage is slower and personally, I don't find it very convenient.

The addition of an RPM package would greatly improve the experience for many RPM-based distribution users.
RPM packages are faster and integrate with the system much better than AppImage. 
Since there is literally no decent alternative to Numara, I built the package myself and decided to propose this idea.

I have also tested the 'publish' script and everything seems to be working. ([Release](https://github.com/arschedev/numara-calculator/releases/tag/v4.0.2))

Thank you for considering this proposal

### CODE REVIEW

**Review by bornova — APPROVED** [review]

**Comment by bornova** [comment]
Hi @arschedev, 
Thanks for the PR, always happy to expand support for more distros.  I will include this in the next release.

**Comment by arschedev** [comment]
Good to hear that!

**Comment by bornova** [comment]
Just released [v4.0.3](https://github.com/bornova/numara-calculator/releases/tag/v4.0.3) with rpm build.  Tried to merge your PR but it failed due to unsigned commits so I just added it to my workflow.  Thank you for your feedback and contribution!

**Comment by arschedev** [comment]
Thank you too

**Pull request closed without merging**
