### PR TITLE
Publish to Windows Package Managar (WinGet)

### PR DESCRIPTION
**Pull request by vedantmgoyal2009**
This action automatically generates manifests for WinGet Community Repository ([microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs)) and submits them.

Before merging this:
1. Please add a GitHub token with `public_repo` scope as a repository secret and rename the secret name in the workflow.
2. Fork [microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs) under @bornova.

### CODE REVIEW

**Comment by vedantmgoyal2009** [comment]
@bornova can you please merge this?

**Comment by vedantmgoyal2009** [comment]
@bornova please review 🙏🏻

**Comment by bornova** [comment]
Hi @vedantmgoyal2009,
Thank you for  your contribution but I don't think Numara is mature enough to be on WinGet yet.  I have other plans for v4.0 and wouldn't consider merging this until at least this new version is released.  This PR also changes the release type on the build workflow which I am not willing to change at the moment.

**Comment by vedantmgoyal2009** [comment]
> This PR also changes the release type on the build workflow which I am not willing to change at the moment.

@bornova this has been resolved...

**Pull request closed without merging**
